[package]
name = "antiq"
version = "0.1.0"
authors = ["Vladimir Zarypov <krre31@gmail.com>"]
edition = "2021"
description = "3DUI toolkit"
repository = "https://github.com/krre/antiq"

[dependencies]
log = "0.4.22"
pollster = "0.4.0"
wgpu = "23.0.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
cfg-if = "1.0.0"

[dev-dependencies]
env_logger = "0.11.5"

[target.'cfg(target_os = "linux")'.dependencies]
wayland-client = "0.31.7"
wayland-protocols = "0.32.5"

[target.'cfg(target_os = "windows")'.dependencies]
windows = "0.58.0"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.26.0"
