[package]
name = "antiq"
version = "0.1.0"
authors = ["Vladimir Zarypov <krre31@gmail.com>"]
edition = "2021"
description = "GUI toolkit"
repository = "https://github.com/krre/antiq"

[dependencies]
log = "0.4.22"
pollster = "0.3.0"
wgpu = "22.1.0"
winit = "0.30.5"
serde = { version = "1.0.206", features = ["derive"] }
serde_json = "1.0.122"

[dev-dependencies]
env_logger = "0.11.5"
