[package]
name = "antiq"
version = "0.1.0"
authors = ["Vladimir Zarypov <krre31@gmail.com>"]
edition = "2021"
description = "Old fashioned, archaic, antiquated GUI toolkit"
repository = "https://github.com/krre/antiq"

[dependencies]
log = "0.4.17"
once_cell = "1.17.1"
pollster = "0.3.0"
wgpu = "0.16.0"
winit = "0.28.3"

[dev-dependencies]
env_logger = "0.10.0"
