[package]
name = "antiq"
version = "0.1.0"
authors = ["Vladimir Zarypov <krre31@gmail.com>"]
edition = "2021"
description = "Old fashioned, archaic, antiquated GUI toolkit"
repository = "https://github.com/krre/antiq"

[dependencies]
log = "0.4.22"
pollster = "0.3.0"
wgpu = "0.16.0"
winit = "0.28.3"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"

[dev-dependencies]
env_logger = "0.11.3"
