[package]
name = "antiq"
version = "0.1.0"
authors = ["Vladimir Zarypov <krre31@gmail.com>"]
edition = "2021"
description = "Old fashioned, archaic, antiquated GUI toolkit"
repository = "https://github.com/krre/antiq"

[dependencies]
wgpu = "0.15.0"
winit = "0.28.1"
